# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Loglkd <- function(Y, Z_beta, gamma_obs) {
    .Call(`_paraflr_Loglkd`, Y, Z_beta, gamma_obs)
}

logis_firth_prov <- function(Y, Z, n_prov, gamma, beta, n_obs, m, threads, tol = 1e-5, max_iter = 10000L, bound = 10.0, message = TRUE, backtrack = FALSE) {
    .Call(`_paraflr_logis_firth_prov`, Y, Z, n_prov, gamma, beta, n_obs, m, threads, tol, max_iter, bound, message, backtrack)
}

Loglkd_firth <- function(Y, Z, n_prov, gamma, beta) {
    .Call(`_paraflr_Loglkd_firth`, Y, Z, n_prov, gamma, beta)
}

wald_gamma <- function(Z, p, n_prov, parm_indices) {
    .Call(`_paraflr_wald_gamma`, Z, p, n_prov, parm_indices)
}

