# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logdet_info <- function(info_gamma, schur) {
    .Call(`_paraflr_logdet_info`, info_gamma, schur)
}

Loglkd <- function(Y, Z_beta, gamma_obs) {
    .Call(`_paraflr_Loglkd`, Y, Z_beta, gamma_obs)
}

Loglkd_firth <- function(Y, Z, n_prov, gamma, beta) {
    .Call(`_paraflr_Loglkd_firth`, Y, Z, n_prov, gamma, beta)
}

logis_firth_prov <- function(Y, Z, n_prov, gamma, beta, n_obs, m, threads, tol = 1e-5, max_iter = 100L, bound = 10.0, message = TRUE, stop = "beta", need_trace = FALSE) {
    .Call(`_paraflr_logis_firth_prov`, Y, Z, n_prov, gamma, beta, n_obs, m, threads, tol, max_iter, bound, message, stop, need_trace)
}

wald_gamma <- function(Z, p, n_prov, parm_indices) {
    .Call(`_paraflr_wald_gamma`, Z, p, n_prov, parm_indices)
}

